name: Unit Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup
        run: pnpm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Lint
        run: nr lint

      - name: Format Check
        run: nr format:check

      - name: Monorepo Check
        run: nr mono:check

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Set node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Setup
        run: pnpm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Type Check
        run: nr typecheck

      - name: Unit Test
        run: nr test

      - name: Build Playground
        run: pnpm run --filter "./playground/*" --parallel build
        if: ${{ matrix.os == 'ubuntu-latest' }}
